title: 개발 여정
email: indigopyj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: " " # the subpath of your site, e.g. /blog
url: "https://indigopyj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: "artemsheludko/adam-blog"
# Author settings
author: 박나깨 # add your name
author-pic: profile.jpg
about-author: 저는 Deep Learning, Computer Vision, AI, Image Processing에 관심이 있는 학생입니다.

# Contact links
email: indigopyj@gmail.com # Add your Email address
phone: # Add your Phone number
website: https://blog.naver.com/revan2426 # Add your website, do not add http://
linkedin: https://www.linkedin.com/in/yeojeong-park-9667201b8/ # Add your Linkedin handle
github: indigopyj # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: indigo # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
